### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by Gu5tavoC** [josa42/atom-svg-preview#10]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Unknown Windows Version
**Thrown From**: [svg-preview](https://github.com/lloeki/svg-preview) package, v0.5.1

### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At module.js:330

Error: Cannot find module 'atom-space-pen-views'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\Gustavo\AppData\Local\atom\app-0.190.0\resources\app\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Gustavo\.atom\packages\svg-preview\lib\svg-preview-view.coffee:3:24)
  at Object.<anonymous> (C:\Users\Gustavo\.atom\packages\svg-preview\lib\svg-preview-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Gustavo\AppData\Local\atom\app-0.190.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at isSvgPreviewView (C:\Users\Gustavo\.atom\packages\svg-preview\lib\main.coffee:10:21)
  at Object.module.exports.toggle (C:\Users\Gustavo\.atom\packages\svg-preview\lib\main.coffee:57:8)
  at atom-workspace.atom.commands.add.svg-preview:toggle (C:\Users\Gustavo\.atom\packages\svg-preview\lib\main.coffee:36:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Gustavo\AppData\Local\atom\app-0.190.0\resources\app\src\command-registry.js:242:29)
  at CommandRegistry.handleCommandEvent (C:\Users\Gustavo\AppData\Local\atom\app-0.190.0\resources\app\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Gustavo\AppData\Local\atom\app-0.190.0\resources\app\src\command-registry.js:157:19)
  at EventEmitter.<anonymous> (C:\Users\Gustavo\AppData\Local\atom\app-0.190.0\resources\app\src\window-event-handler.js:73:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:28.1 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:04.3 svg-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
language-svg, v0.8.0
minimap, v4.7.6
svg-preview, v0.5.1

# Dev
No dev packages
```

**Comment by pekko666** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [svg-preview](https://github.com/lloeki/svg-preview) package, v0.6.0


### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At module.js:330

Error: Cannot find module 'atom-space-pen-views'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\makelpe99\AppData\Local\atom\app-0.211.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\makelpe99\.atom\packages\svg-preview-master\lib\svg-preview-view.coffee:3:24)
  at Object.<anonymous> (C:\Users\makelpe99\.atom\packages\svg-preview-master\lib\svg-preview-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\makelpe99\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at isSvgPreviewView (C:\Users\makelpe99\.atom\packages\svg-preview-master\lib\main.coffee:10:21)
  at Object.module.exports.toggle (C:\Users\makelpe99\.atom\packages\svg-preview-master\lib\main.coffee:58:8)
  at atom-workspace.atom.commands.add.svg-preview:toggle (C:\Users\makelpe99\.atom\packages\svg-preview-master\lib\main.coffee:37:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\makelpe99\AppData\Local\atom\app-0.211.0\resources\app.asar\src\command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (C:\Users\makelpe99\AppData\Local\atom\app-0.211.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\makelpe99\AppData\Local\atom\app-0.211.0\resources\app.asar\src\command-registry.js:156:19)
  at EventEmitter.<anonymous> (C:\Users\makelpe99\AppData\Local\atom\app-0.211.0\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:21.3.0 svg-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by lloeki** [comment]
Is this still a problem? If so, did you try starting with a clean settings folder?

**Comment by josa42** [comment]
Is this still an issue?

**Comment by mathsbeauty** [comment]
:\Users\admin\AppData\Local\atom\app-1.14.4\resources\electron.asar\common\reset-search-paths.js:0
Hide Stack Trace
Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\admin\AppData\Local\atom\app-1.14.4\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\admin\AppData\Local\atom\app-1.14.4\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\admin\AppData\Local\atom\app-1.14.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/admin/.atom/packages/atom-svg-preview-master/lib/svg-preview-view.js:4:70)
    at Module._compile (C:\Users\admin\AppData\Local\atom\app-1.14.4\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\admin\AppData\Local\atom\app-1.14.4\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\admin\AppData\Local\atom\app-1.14.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at importSvgPreviewView (file:///C:/Users/admin/.atom/packages/atom-svg-preview-master/lib/main.js:10:22)
    at isSvgPreviewView (file:///C:/Users/admin/.atom/packages/atom-svg-preview-master/lib/main.js:20:3)
    at Object.toggle (file:///C:/Users/admin/.atom/packages/atom-svg-preview-master/lib/main.js:130:9)
    at atom-workspace.svgPreviewToggle (file:///C:/Users/admin/.atom/packages/atom-svg-preview-master/lib/main.js:42:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\admin\AppData\Local\atom\app-1.14.4\resources\app.asar\src\command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (C:\Users\admin\AppData\Local\atom\app-1.14.4\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\admin\AppData\Local\atom\app-1.14.4\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\admin\AppData\Local\atom\app-1.14.4\resources\app.asar\src\atom-environment.js:1164:28)
    at EventEmitter.outerCallback (C:\Users\admin\AppData\Local\atom\app-1.14.4\resources\app.asar\src\application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
