### ISSUE TITLE
Uncaught Error: The specified procedure could not be found.C:\Users\amits\.atom\packages\svg-preview\node_modules\pathwatcher\build\Release\pathwatcher.node

### ISSUE THREAD

**Issue by amitmtrn** [josa42/atom-svg-preview#9]
1. tried to open svg preview on svg file

**Atom Version**: 0.189.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [svg-preview](https://github.com/lloeki/svg-preview) package, v0.5.1

### Stack Trace

Uncaught Error: The specified procedure could not be found.
C:\Users\amits\.atom\packages\svg-preview\node_modules\pathwatcher\build\Release\pathwatcher.node

```
At ATOM_SHELL_ASAR.js:118

Error: The specified procedure could not be found.
C:\Users\amits\.atom\packages\svg-preview\node_modules\pathwatcher\build\Release\pathwatcher.node
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\amits\.atom\packages\svg-preview\node_modules\pathwatcher\lib\main.js:6:13)
  at Object.<anonymous> (C:\Users\amits\.atom\packages\svg-preview\node_modules\pathwatcher\lib\main.js:207:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\amits\AppData\Local\atom\app-0.189.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\amits\.atom\packages\svg-preview\lib\svg-preview-view.coffee:5:10)
  at Object.<anonymous> (C:\Users\amits\.atom\packages\svg-preview\lib\svg-preview-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\amits\AppData\Local\atom\app-0.189.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at isSvgPreviewView (C:\Users\amits\.atom\packages\svg-preview\lib\main.coffee:10:21)
  at Object.module.exports.toggle (C:\Users\amits\.atom\packages\svg-preview\lib\main.coffee:57:8)
  at atom-workspace.atom.commands.add.svg-preview:toggle (C:\Users\amits\.atom\packages\svg-preview\lib\main.coffee:36:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\amits\AppData\Local\atom\app-0.189.0\resources\app\src\command-registry.js:242:29)
  at c:\Users\amits\AppData\Local\atom\app-0.189.0\resources\app\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (c:\Users\amits\AppData\Local\atom\app-0.189.0\resources\app\node_modules\command-palette\lib\command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (c:\Users\amits\AppData\Local\atom\app-0.189.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (c:\Users\amits\AppData\Local\atom\app-0.189.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\amits\AppData\Local\atom\app-0.189.0\resources\app\src\command-registry.js:242:29)
  at c:\Users\amits\AppData\Local\atom\app-0.189.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (c:\Users\amits\AppData\Local\atom\app-0.189.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:552:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (c:\Users\amits\AppData\Local\atom\app-0.189.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:392:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (c:\Users\amits\AppData\Local\atom\app-0.189.0\resources\app\src\window-event-handler.js:180:20)

```

### Commands

```
     -0:09.5 command-palette:toggle (atom-text-editor.editor)
     -0:07.9 core:confirm (atom-text-editor.editor.mini)
     -0:07.9 svg-preview:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint",
      "script"
    ],
    "autoHideMenuBar": true,
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "svg-preview": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.8.0
emmet, v2.3.6
linter, v0.12.0
linter-jscs, v1.10.0
linter-jshint, v0.1.1
monokai, v0.13.0
remote-edit, v1.7.2
svg-preview, v0.5.1

# Dev
No dev packages
```

**Comment by lloeki** [comment]
Is this still a problem? If so, did you try with a clean settings folder?

**Comment by josa42** [comment]
Is this still an issue?
